/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppHome: typeof import('./src/components/layout/AppHome.vue')['default']
    AppTags: typeof import('./src/components/layout/AppTags.vue')['default']
    BarModel: typeof import('./src/components/echartsModel/BarModel.vue')['default']
    CylinderModel: typeof import('./src/components/echartsModel/CylinderModel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    FleetModel: typeof import('./src/components/FleetModel.vue')['default']
    LineModel: typeof import('./src/components/echartsModel/LineModel.vue')['default']
    MenusItem: typeof import('./src/components/menus/MenusItem.vue')['default']
    PictorialBarModel: typeof import('./src/components/echartsModel/PictorialBarModel.vue')['default']
    PieModel: typeof import('./src/components/echartsModel/PieModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScatterModel: typeof import('./src/components/echartsModel/ScatterModel.vue')['default']
    SideMenu: typeof import('./src/components/menus/SideMenu.vue')['default']
  }
}
